name: Tests

on:
  push:
  pull_request:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y cmake portaudio19-dev libasound2-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Run Python tests
      run: |
        # Set environment variables for headless audio testing
        export PULSE_RUNTIME_PATH=/tmp/pulse
        export PULSE_CONFIG_PATH=/tmp/pulse
        export PULSE_STATE_PATH=/tmp/pulse
        pytest
